---

# ZSH config

- include_role:
    name: dotfiles

- include_role:
    name: vaulttec.zsh
  vars:
    zsh_ohmy_theme: robbyrussell
    zsh_ohmy_plugins: [git]
  when: ansible_user_shell.split('/')[-1] != 'zsh'


- name: Create .zshrc config symlinks
  file:
    src: "/home/{{ user }}/dotfiles/{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
    force: yes
    group: "{{ user }}" 
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - ".zshrc"
    - ".shrc.d"
