---

- hosts: localhost
  connection: local
  roles:
#    - python3-versions
    - utilities-base
    - utilities-laptop
    - utilities-cloud
    - neovim
    - docker
    - dbeaver
    - mullvad
    - asdf
    - dotfiles