---

- name: Install essential packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - curl
      - tree
      - tmux
      - git
      - htop
      - python
      - python-pip
      - xclip
      - jq
      - nmap
    state: present