---

- name: Install essential packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - curl
      - tree
      - tmux
      - git
      - htop
      - xclip
      - jq
      - nmap
    state: present