---

- name: Check if dotfiles exist
  stat:
    path: "/home/{{ user }}/dotfiles"
  register: dotfiles_dir

- name: Download dotfiles
  git:
    repo: https://github.com/afdezl/dotfiles.git
    dest: "/home/{{ user }}/dotfiles"
  when: dotfiles_dir.stat.exists == false


- name: Create config symlinks
  file:
    src: "/home/{{ user }}/dotfiles/{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
    force: yes
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - ".bashrc"
    - ".shrc.d"
    - ".tmux.conf"
