---

# Download personal configuration dotfiles

- name: Download dotfiles
  git:
    repo: https://github.com/afdezl/dotfiles.git
    dest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles"  


- name: Create .rc config symlinks
  file:
    src: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/{{ item }}"
    dest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/{{ item }}"
    state: link
    force: yes
    group: "{{ ansible_ssh_user|default(lookup('env', 'USER')) }}" 
    owner: "{{ ansible_ssh_user|default(lookup('env', 'USER')) }}"
    mode: 0700
  
  with_items:
    - ".bashrc"
    - ".zshrc"
    - ".shrc.d"


