---

- name: Add KeepassXC repository
  become: true
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present
    update_cache: yes


- name: Install KeepassXC
  become: true
  apt:
    pkg: keepassxc
    state: present
    update_cache: yes
