# Laptop configuration file

- name: add apt-keys
  become: true
  apt_key: url='https://download.sublimetext.com/sublimehq-pub.gpg' state=present


- name: add repositories
  become: true
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - 'deb https://download.sublimetext.com/ apt/stable/' 
    - 'deb http://repository.spotify.com stable non-free'
    - 'ppa:phoerious/keepassxc'
    - 'ppa:octave/stable'
    - 'deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner'


- name: install apt packages
  become: true
  action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - virtualbox
    - vagrant
    - sublime-text
    - spotify-client
    - hugo
    - whois
    - keepassxc
    - network-manager-openvpn
    - smem
    - inkscape
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - ubuntu-restricted-extras
    - build-essential
    - nodejs
    - npm
    - octave


- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

