---

# Laptop configuration file

- include_role:
    name: dotfiles


- name: Add apt-keys
  become: true
  apt_key: url={{ item }} state=present
  with_items:
    - 'https://download.sublimetext.com/sublimehq-pub.gpg'
    - 'https://repo.skype.com/data/SKYPE-GPG-KEY'


- name: Add repositories
  become: true
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - 'deb https://download.sublimetext.com/ apt/stable/' 
    - 'deb http://repository.spotify.com stable non-free'
    - 'ppa:phoerious/keepassxc'
    - 'ppa:octave/stable'
    - 'deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner'
    - 'deb [arch=amd64] https://repo.skype.com/deb unstable main'


- name: Install apt packages
  become: true
  action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - virtualbox
    - vagrant
    - sublime-text
    - spotify-client
    - hugo
    - whois
    - keepassxc
    - network-manager-openvpn
    - smem
    - inkscape
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - ubuntu-restricted-extras
    - build-essential
    - octave
    - skypeforlinux
    - paprefs
    - pavucontrol
    - cifs-utils


- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: slack_installed.rc > 1
  changed_when: slack_installed.rc == 1


- name: Check if dbeaver is installed
  command: dpkg-query -W dbeaver
  register: dbeaver_installed
  failed_when: dbeaver_installed.rc > 1
  changed_when: dbeaver_installed.rc == 1


- name: Download remote packages
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: 0777
  with_items:
    - { url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb", destination: "/tmp/slack.deb"}
    - { url: "https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb", destination: "/tmp/dbeaver.deb"}


- name: Install Slack
  become: true
  apt:
    deb: "/tmp/slack.deb"
  when: slack_installed.rc == 1


- name: Install DBeaver
  become: true
  apt:
    deb: "/tmp/dbeaver.deb"
  when: dbeaver_installed.rc == 1


- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes


- name: Create required directories in $HOME
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - "projects"


- name: Create .bashrc config symlinks
  file:
    src: "/home/{{ user }}/dotfiles/{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
    force: yes
    group: "{{ user }}" 
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - ".bashrc"
    - ".shrc.d"




