---

- include_role:
    name: dotfiles


- name: Install apt packages
  become: true
  apt:
    pkg:
      - whois
      - network-manager-openvpn
      - smem
      - inkscape
      - postgresql
      - postgresql-contrib
      - postgresql-client
    update_cache: yes


- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: slack_installed.rc > 1
  changed_when: slack_installed.rc == 1


- name: Check if dbeaver is installed
  command: dpkg-query -W dbeaver
  register: dbeaver_installed
  failed_when: dbeaver_installed.rc > 1
  changed_when: dbeaver_installed.rc == 1


- name: Download remote packages
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: 0777
  with_items:
    - { url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb", destination: "/tmp/slack.deb"}
    - { url: "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb", destination: "/tmp/dbeaver.deb"}
  when:
    - dbeaver_installed.rc == 1 or slack_installed.rc == 1

- name: Install Slack
  become: true
  apt:
    deb: "/tmp/slack.deb"
  when: slack_installed.rc == 1


- name: Install DBeaver
  become: true
  apt:
    deb: "/tmp/dbeaver.deb"
  when: dbeaver_installed.rc == 1


- name: Create required directories in $HOME
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - "projects"


- name: Create .bashrc config symlinks
  file:
    src: "/home/{{ user }}/dotfiles/{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    state: link
    force: yes
    group: "{{ user }}" 
    owner: "{{ user }}"
    mode: 0700
  with_items:
    - ".bashrc"
    - ".shrc.d"


- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes
