---

- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: slack_installed
  failed_when: slack_installed.rc > 1
  changed_when: slack_installed.rc == 1

- name: Download remote package
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: 0777
  with_items:
    - { url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ version }}-amd64.deb", destination: "/tmp/slack.deb"}
  when:
    - slack_installed.rc == 1

- name: Install Slack
  become: true
  apt:
    deb: "/tmp/slack.deb"
  when: slack_installed.rc == 1
