---

- name: Install dependencies
  become: true
  apt:
    package: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - automake
    - autotools-dev
    - fuse
    - g++
    - git
    - libcurl4-gnutls-dev
    - libfuse-dev
    - libssl-dev
    - libxml2-dev
    - make
    - pkg-config


- name: Download s3fs-fuse
  git:
    repo: https://github.com/s3fs-fuse/s3fs-fuse.git
    dest: "/home/{{ user }}/projects/s3fs-fuse"
