---

# Main configuration file for cmmon packages and config

- name: Ensure aptitude and apt properties are installed
  become: true
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - aptitude
    - apt-transport-https
    - software-properties-common


- name: Add repositories
  become: true
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - 'ppa:git-core/ppa'
    - 'ppa:jonathonf/python-3.6'
  when: ansible_distribution_release != "stretch"


- name: Install packages
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - make
    - tree
    - vim
    - tmux
    - git
    - git-core
    - htop
    - python
    - python3.6
    - python-pip
    - xclip
    - jq
    - nmap

