---

- name: Install dependencies
  become: true
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
    state: present


- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Add Docker repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    update_cache: yes


- name: Install docker-ce
  become: true
  apt:
    pkg: docker-ce
    state: present


