---

- name: Install dependencies
  become: true
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
    state: present


- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Add Docker repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    update_cache: yes


- name: Install docker-ce
  become: true
  apt:
    pkg: docker-ce
    state: present


- name: Generate docker compose download name
  shell: echo docker-compose-$(uname -s)-$(uname -m)
  register: get_download_name
  changed_when: false

- name: Check if docker-compose installed
  shell: docker-compose --version
  register: docker_compose
  changed_when: false

- name: Download docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/{{ get_download_name.stdout }}"
    dest: /tmp/docker-compose
    owner: root
    group: root
    mode: 0775
  when: docker_compose.rc != 0


- name: Install docker compose
  become: true
  copy:
    src: /tmp/docker-compose
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: docker_compose.rc != 0
