---

- name: Add repositories
  become: true
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - 'ppa:octave/stable'


- name: Install apt packages
  become: true
  apt:
    pkg:
      - octave
    update_cache: yes
