# Installation of RPi specific dev libraries

- name: Install dev packages
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - libbluetooth-dev
    - libnss-mdns
    - nodejs
    - npm


- name: Install python packages
  become: true
  pip: name={{ item }} state=present
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython
    - utilities-cloud
    - PyYaml
