---

- name: Add neovim repository
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes


- name: Install neovim
  become: true
  apt:
    pkg: neovim
    state: present


- name: Create neovim directory
  file:
    path: ~/.config/nvim
    state: directory

- name: Create vimplug entry
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ user }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0644
