---

- name: Add neovim repository
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes


- name: Install neovim
  become: true
  apt:
    pkg: neovim
    state: present


- name: Create required directories
  file:
    dest: ~/.config/nvim
    mode: 0755
    state: directory

- name: Create required files
  file:
    dest: ~/.config/nvim/init.vim
    mode: "u=rw,g=rw,o=r"
    state: touch

- name: Add NVim config
  lineinfile:
    dest: ~/.config/nvim/init.vim
    line: set guicursor=
    state: present
    create: yes